#!/usr/bin/env node

/**
 * Demo script for Cursor Code Tracking Extension
 * This simulates the extension's functionality for testing purposes
 */

const fs = require('fs-extra');
const path = require('path');

// Simulate the extension's tracking logic
class DemoCodeTracker {
    constructor() {
        this.lineData = new Map();
        this.stats = { humanLines: 0, llmLines: 0 };
    }

    // Simulate line classification
    classifyLine(content, lineNumber) {
        // Simple heuristics for demo purposes
        const isLLM = content.length > 50 || content.includes('AI') || content.includes('generated');
        const origin = isLLM ? 'LLM' : 'HUMAN';
        
        this.recordLine(lineNumber, origin);
        return origin;
    }

    recordLine(lineNumber, origin) {
        if (!this.lineData.has('demo')) {
            this.lineData.set('demo', []);
        }
        
        this.lineData.get('demo').push({
            lineNumber,
            origin,
            timestamp: Date.now()
        });

        if (origin === 'HUMAN') {
            this.stats.humanLines++;
        } else {
            this.stats.llmLines++;
        }
    }

    getStats() {
        const total = this.stats.humanLines + this.stats.llmLines;
        const ratio = total > 0 ? `${Math.round((this.stats.humanLines / total) * 100)}% human` : '0% human';
        
        return {
            ...this.stats,
            ratio,
            total
        };
    }

    generateReport() {
        const stats = this.getStats();
        const report = {
            human_lines: stats.humanLines,
            llm_lines: stats.llmLines,
            ratio: stats.ratio,
            timestamp: new Date().toISOString(),
            files_analyzed: this.lineData.size
        };

        return report;
    }
}

// Demo function
async function runDemo() {
    console.log('🎯 Cursor Code Tracking Extension Demo');
    console.log('=====================================\n');

    const tracker = new DemoCodeTracker();

    // Simulate some code changes
    const demoLines = [
        '// This is a simple comment',
        'function calculateSum(a, b) {',
        '    return a + b;',
        '}',
        '',
        '// AI-generated function for complex calculations',
        'function performComplexCalculation(input) {',
        '    // This function was generated by an AI assistant',
        '    // It handles complex mathematical operations',
        '    const result = input.map(x => x * 2).filter(x => x > 10).reduce((a, b) => a + b, 0);',
        '    return result;',
        '}',
        '',
        '// Human-written test function',
        'function testCalculation() {',
        '    console.log("Testing...");',
        '}'
    ];

    console.log('📝 Analyzing demo code...\n');

    // Process each line
    demoLines.forEach((line, index) => {
        const origin = tracker.classifyLine(line, index);
        const icon = origin === 'LLM' ? '🌐' : '✏️';
        console.log(`${icon} Line ${index + 1}: ${line.substring(0, 50)}${line.length > 50 ? '...' : ''}`);
    });

    console.log('\n📊 Statistics:');
    const stats = tracker.getStats();
    console.log(`- Human lines: ${stats.humanLines}`);
    console.log(`- LLM lines: ${stats.llmLines}`);
    console.log(`- Ratio: ${stats.ratio}`);
    console.log(`- Total lines: ${stats.total}`);

    console.log('\n📄 Generated Report:');
    const report = tracker.generateReport();
    console.log(JSON.stringify(report, null, 2));

    // Simulate saving report
    const reportDir = path.join(process.cwd(), '.cursor', 'stats');
    await fs.ensureDir(reportDir);
    
    const reportPath = path.join(reportDir, 'demo_report.json');
    await fs.writeJson(reportPath, report, { spaces: 2 });
    
    console.log(`\n💾 Report saved to: ${reportPath}`);

    // Check threshold
    const llmPercentage = stats.total > 0 ? (stats.llmLines / stats.total) * 100 : 0;
    const threshold = 70;
    
    if (llmPercentage > threshold) {
        console.log(`\n⚠️  Warning: ${llmPercentage.toFixed(1)}% of code is LLM-generated (threshold: ${threshold}%)`);
    } else {
        console.log(`\n✅ LLM code percentage (${llmPercentage.toFixed(1)}%) is below threshold (${threshold}%)`);
    }

    console.log('\n🎉 Demo completed!');
    console.log('\nTo use the actual extension:');
    console.log('1. Run: ./install.sh');
    console.log('2. Restart Cursor');
    console.log('3. Edit files to see real-time tracking');
}

// Run the demo
runDemo().catch(console.error); 